### ISSUE TITLE
Training with Accelerator 

### ISSUE THREAD

**Issue by shbkukuk** [nachifur/RDDM#35]
Firstly, I would you like for proposing project that is amazing. I am working on paired image 2 image translation project. So i want to try your approach. I read your codes and use the train script on the dog_2_cat. When i start train with multi GPU launch on Accelerator, training is going on but after the sampling process for test dataset i get timeout Error. I will share the error in the below. Do You have any idea that how i cross with this Error ? 

```RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=25, OpType=BROADCAST, Timeout(ms)=1800000) ran for 1801490 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 164237 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 164238) of binary: /home/virasoft/miniconda3/envs/i2sb/bin/python
Traceback (most recent call last):
  File "/home/virasoft/miniconda3/envs/i2sb/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/virasoft/miniconda3/envs/i2sb/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/home/virasoft/miniconda3/envs/i2sb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 1165, in launch_command
    multi_gpu_launcher(args)
  File "/home/virasoft/miniconda3/envs/i2sb/lib/python3.8/site-packages/accelerate/commands/launch.py", line 799, in multi_gpu_launcher
    distrib_run.run(args)
  File "/home/virasoft/miniconda3/envs/i2sb/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/virasoft/miniconda3/envs/i2sb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/virasoft/miniconda3/envs/i2sb/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-26_19:24:32
  host      : virasoft-System-Product-Name
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 164238)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html```


I start training like this code :
```accelerate launch train.py```

**Comment by nachifur** [comment]
You can debug the code.
1. try to run model on the train dataset.
2. shuffle=False in dataloader.
