### ISSUE TITLE
Why report this error so soon after training：TypeError: GaussianDiffusion.sample() got an unexpected keyword argument 'last'

### ISSUE THREAD

**Issue by 1164959318** [nachifur/RDDM#46]
D:\ProgramData\anaconda3\envs\diff\python.exe D:\DDPM\RDDM\experiments\2_Image_Restoration_deraing_raindrop_noise1\train.py 
loss: 0.0600:  83%|████████▎ | 999/1200 [49:00<09:51,  2.94s/it]
Traceback (most recent call last):
  File "D:\DDPM\RDDM\experiments\2_Image_Restoration_deraing_raindrop_noise1\train.py", line 126, in <module>
    trainer.train()
  File "D:\DDPM\RDDM\experiments\2_Image_Restoration_deraing_raindrop_noise1\src\residual_denoising_diffusion_pytorch.py", line 1366, in train
    self.sample(milestone)
  File "D:\DDPM\RDDM\experiments\2_Image_Restoration_deraing_raindrop_noise1\src\residual_denoising_diffusion_pytorch.py", line 1401, in sample
    list(self.ema.ema_model.sample(
  File "D:\ProgramData\anaconda3\envs\diff\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: GaussianDiffusion.sample() got an unexpected keyword argument 'last'

Why report this error so soon after training？

**Comment by nachifur** [comment]
For 2_Image_Restoration_deraing_raindrop_noise1\train.py, we use ResidualDiffusion.sample() rather than GaussianDiffusion.sample(). This error occurs because you have changed the default configuration.
